config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :books

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Returns the current use if logged in
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in a filter to ensure the user is logged in
  def authorize!
    redirect_to login_path unless logged_in?
  end

  def index
    @books = Books.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authorize!

  # GET /Books
  def index
    @books = Book.all
  end

  # GET /Books/1
  def show
    @book = Book.find(params[:id])
  end

  # GET /Books/new
  def new
    @book = Book.new
  end

  # GET /Books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # Book /Books
  def create
    @book = Book.new(Book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /Books/1
  def update
    @book = Book.find(params[:id])
    if @book.update(Book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /Books/1
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to Books_url, notice: 'Book was successfully destroyed.'
  end

  private

  # Only allow a trusted parameter "white list" through.
  def Book_params
    params.require(:book).permit(:title, :author, :description, :url)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    # Extract the email and password from the params
    email = params[:email]
    password = params[:password]

    # Find the user by their email
    user = User.find_by(email: email)

    # If we found a user and their password checks out
    if user && user.authenticate(password)
      # Save the user_id in the session cookie
      session[:user_id] = user.id

      # logged in!
      redirect_to root_path
    else
      # Nope, something went wrong
      redirect_to login_path
      flash.alert = "Invalid email and/or password."
    end
  end

  # logout
  def destroy
    # Remove their user_id from the session
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
      def new
        @user = User.new
      end

      def create
        user = User.new(user_params)
        if user.save
          session[:user_id] = user.id
          # redirect_to logout_path, alert: "You've successfully registered an account."
          redirect_to root_path
        else
          redirect_to signup_path
        end
      end

    private

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, html: { class: "form-horizontal", role: "form" }) do |f| %>

  <%# Alert showing errors for this form %>
  <% if @book.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h4>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# title %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>


  <%# author %>
  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>


  <%# description %>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>


  <%# url %>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>


  <%# Submit %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end -%>

app/views/books/edit.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @book, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Edit Book Details</h1>
</div>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="page-header">
  <%= link_to new_book_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New book
  <% end %>
  <h1 Listing>Books</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <!-- <th>Title</th> -->
        <th>Author</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody class="table-body">
      <%- @books.each do |book| %>
      <tr>
        <td><%= image_tag(book.url, height: "100") %><br><%= book.title %></td>
        <!-- <td><%= book.title %></td> -->
        <td><%= book.author %></td>
        <td><%= book.description %></td>
        <td>
          <%= link_to book do %>
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_book_path(book) do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          <% end %>
        </td>
        <td>
          <%= link_to book, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/books/new.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Add a Book</h1>
</div>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_book_path(@book), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>View Book Details</h1>
</div>

<dl class="dl-horizontal">
  <%= image_tag(@book.url, height: "200") %>
  <dt>Title:</dt>
  <dd><%= @book.title %></dd>

  <dt>Author:</dt>
  <dd><%= @book.author %></dd>

  <dt>Description:</dt>
  <dd><%= @book.description %></dd>

  <dt>Url:</dt>
  <dd><%= @book.url %></dd>


</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>
    <%= Rails.application.class.parent_name %>
  </title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller_name%> action-<%= action_name%>">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "#", class: "navbar-brand" do %>
          Freeshelf
        <% end %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", "/books" %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <% if logged_in? %>
    Logged in: <%= current_user.email %> | <%= link_to "Logout", logout_path %>
    <% else %>
    <%= link_to 'Login', login_path %> | <%= link_to 'Signup', signup_path %>
    <% end %>
    <%= yield %>

  </div>
</body>
</html>

app/views/session/new.html.erb
<h1>Login</h1>

<!-- <%= form_tag login_path do %>
  Email: <%= text_field_tag :email %>
  Password: <%= password_field_tag :password %>
  <%= submit_tag "Submit" %>
<% end %> -->

<%= form_tag login_path do %>
<div class="container" style="margin-top:30px">
  <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong>Login </strong></h3>
          <!-- <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a>
          </div> -->
        </div>

  <div class="panel-body">
   <form role="form">
   <!-- <div class="alert alert-danger">
      <a class="close" data-dismiss="alert" href="#">×</a>Incorrect Username or Password!
  </div> -->
  <div style="margin-bottom: 12px" class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="Email">
  </div>

  <div style="margin-bottom: 12px" class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <input id="login-password" type="password" class="form-control" name="password" placeholder="Password">
  </div>

  <div class="input-group">
    <div class="checkbox" style="margin-top: 0px;">
      <label>
        <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
      </label>
    </div>
  </div>

  <button type="submit" class="btn btn-success">Login</button>

  <hr style="margin-top:10px;margin-bottom:10px;" >

  <div class="form-group">
    <div style="font-size:85%">
      Don't have an account?
      <%= link_to 'Sign up here', signup_path %>
    </div>
  </div>
  </form>
  </div>
  </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>

    <!-- <%= form_for(@user) do |f| %>
      Email: <%= f.text_field :email %>
      Password: <%= f.password_field :password %>
      Password Confirmation: <%= f.password_field :password_confirmation %>
      <%= f.submit "Submit" %>
    <% end %> -->


    <div class="container" style="margin-top:30px">
      <div class="col-md-4 col-md-offset-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><strong>Sign Up </strong></h3>
              <!-- <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a>
              </div> -->
            </div>

      <div class="panel-body">
        <%= form_for(@user) do |f| %>
       <!-- <form role="form"> -->
      <div style="margin-bottom: 12px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>

      <div style="margin-bottom: 12px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>

      <div style="margin-bottom: 12px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password" %>
      </div>

      <button type="submit" class="btn btn-success">Sign up</button>

      <hr style="margin-top:10px;margin-bottom:10px;" >

      <div class="form-group">
        <div style="font-size:85%">
          Already have an account?
          <%= link_to 'Login here', login_path %>
        </div>
      </div>
      </form>
      </div>
      </div>
      </div>
    </div>
    <% end %>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<br>

<%= link_to 'Add a Book', new_book_path %> |
<%= link_to 'View Inventory', books_path %>